# 設定名
profile = "6時に起きよう"

# messageには以下の要素がキーワード引数の形で渡されてformatされる
# current: 現在の時刻(datetime)
# delta: 指定時刻までの時間(datetime.hour)
# 例:
message = "もう{current.hour}時だよ!あと{delta}時間しか眠れないよ!"

# 残りがこの時間になったらカウントダウンを始める
countdown_start_hours = 12

# 残りがこの時間になったらカウントダウンをやめる
countdown_end_hours = 5
# countdown_end_hoursを切ったら以下のメッセージを出力して終了する
sleep_message = "それではもう寝ます。おやすみなさい。"

[weekdays]
sun = "6:00"
mon = "6:00"
tue = "6:00"
wed = "6:00"
thu = "6:00"
fri = "6:00"
sat = "6:00"
